- hosts: all
  roles:
    - role: ensure-tox
      ensure_global_symlinks: true
  tasks:
    - name:  Run tools/gate/build-images docker
      command: bash -xe tools/gate/build-images docker
      args:
        chdir: '{{ zuul.project.src_dir }}'
