- hosts: all
  name: Copy artifacts
  tasks:
    - name: Ensure artifacts directory exists
      file:
        path: "{{ zuul.executor.work_root }}/artifacts"
        state: directory
      delegate_to: localhost
    - name: Collect artifacts
      synchronize:
        dest: "{{ zuul.executor.work_root }}/artifacts/images/"
        mode: pull
        src: "{{ zuul.project.src_dir }}/images/"
        copy_links: true
        verify_host: true
        rsync_opts:
          - --filter=P, *.qcow2
          - --include=**
          - --delete
