- project:
    templates:
      - check-requirements
      - build-openstack-docs-pti
      - openstack-lower-constraints-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - manila-image-elements-buildimages
        - manila-image-elements-buildimage-docker
        - manila-tempest-dsvm-container-scenario-custom-image:
            voting: false
            irrelevant-files: &irrelevant-files
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^.*\.rst$
              - ^doc/.*$
              - ^tox.ini$
        - manila-image-elements-generic-scenario:
            voting: false
            irrelevant-files: *irrelevant-files
    gate:
      jobs:
        - openstack-tox-pep8
        - manila-image-elements-buildimages
    post:
      jobs:
        - manila-image-elements-publish-artifacts
